x-spark-common: &spark-common
  image: wlcamargo/spark-master
  networks:
    - sparkanos
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  spark-master:
    <<: *spark-common
    hostname: spark-master
    container_name: spark-master
    command: 
      - /bin/sh
      - -c
      - |
        /usr/local/spark/sbin/start-master.sh
        start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./conf/util:/util
      - ./conf/env:/env
      - ${NOTEBOOK_PATH}:/home/user/work
    ports:
      - 8889:8888 # Jupyter
      - 8083:8080 # Spark UI
      - 4040:4040 # Spark UI Jobs
      - 7077:7077 # Default port for communication

  spark-worker1:
    <<: *spark-common
    hostname: spark-worker1
    container_name: spark-worker1
    command: 
      - /bin/sh
      - -c
      - |
        /usr/local/spark/sbin/start-worker.sh spark-master:7077
        start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./conf/util:/util
      - ./conf/env:/env
    ports:
      - 5043:4040
      - 5044:4041
    depends_on:
      - spark-master

  spark-worker2:
    <<: *spark-common
    hostname: spark-worker2
    container_name: spark-worker2
    command: 
      - /bin/sh
      - -c
      - |
        /usr/local/spark/sbin/start-worker.sh spark-master:7077
        start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./conf/util:/util
      - ./conf/env:/env
    ports:
      - 5045:4041
      - 5046:4042
    depends_on:
      - spark-master

networks:
  sparkanos:
    external: true
